### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by ForHemer** [Micky373/My_portfolio#11]
- [x] @ForHemer : Congratulations @Micky373 :clap:. You did a wonderful job :100:. The only advice is to put a `text align: center;` to your email validator to fit your mobile version.

- [x] @Behnam1369 :

1. You are using two different menus for desktop and mobile which is not necessary. Instead, you can use media queries to change the style. It's better to put menu items inside `<nav>`.
2.  You can make your popup window scrollable. 
3.  You need to fix `regex` constraint that prevents submitting the correct email address 

- [ ]  @AlejandroNeira98 :

1. Scale Gym image with height to 100% 
2. Make the card container a `flex with column` direction to fix button position

**Comment by Micky373** [comment]
Thank you!!
